name: situacao_aprendizagem_recursos_hardware
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sqflite: ^2.3.3
  path: ^1.9.1 
  image_picker: ^1.0.7
  geolocator: ^11.0.0
  permission_handler: ^11.3.1
  flutter_ringtone_player: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
